### ISSUE TITLE
stack overflow in quantizer_wu.rs

### ISSUE THREAD

**Issue by tehrelt** [Aiving/material-colors#32]
thread 'main' has overflowed its stack

```rust
use material_colors::{
    image::{FilterType, ImageReader},
    theme::ThemeBuilder,
};

#[tokio::main]
async fn main() -> Result<(), reqwest::Error> {
    let image = reqwest::get("https://picsum.photos/200/300")
        .await?
        .bytes()
        .await?
        .to_vec();

    let mut data = ImageReader::read(image).expect("failed to read image");

    data.resize(128, 128, FilterType::Nearest);
    let theme = ThemeBuilder::with_source(ImageReader::extract_color(&data)).build();

    Ok(())
}
```

Cargo.toml
```toml
[dependencies]
material-colors = { version = "0.4", features = ["image", "std", "serde"] }
reqwest = "0.12.5"
tokio = { version = "1.39.2", features = ["full"] }

[dev-dependencies]

```

![terminal output](https://github.com/user-attachments/assets/19072c1b-08cb-40da-971b-d49a0aa281ea)
![debug image](https://github.com/user-attachments/assets/1890834a-7c29-481b-8fa9-f3d5308fd529)

_Originally posted by @tehrelt in https://github.com/Aiving/material-colors/issues/31#issuecomment-2261336034_
